### ISSUE TITLE
Google fix the extension and cannot get key anymore

### ISSUE THREAD

**Issue by georgysaumen** [parnexcodes/widevine-l3-guesser-modified#16]
Hello,

As I see, Google has fixed the extension and i cannot get key for decrypt through the extension anymore. Can you give a look with this and create new ?

Thanks!

**Comment by dreamhd2015** [comment]
True, since yesterday it does not work on any website, could it have a solution?

**Comment by georgysaumen** [comment]
> True, since yesterday it does not work on any website, could it have a solution?

I think you give a look with this, i don't know they work or not:  https://github.com/xhlove/WVClient3

**Comment by parnexcodes** [comment]
CDM has been updated I think.

**Comment by ghost** [comment]
Work just fine here :-)

**Comment by barepixels** [comment]
Confirm, Chrome just update 5 minutes ago and the Guesser stop working.  Grrrr  I am in the middle of ripping.

DO NOT UPDATE TO Version 95.0.4638.54 (Official Build) (64-bit)  I went to about chrome and it auto starts updating

Good news I use other Chrome based browser and the Guesser still works there.

**Comment by georgysaumen** [comment]
You can download Brave browser and is work normally

Vào Th 6, 22 thg 10, 2021 vào lúc 16:52 barepixels <
***@***.***> đã viết:

**Comment by VitusCitrus** [comment]
Brave works fine. Does someone has a link to the latest chrome portable version that still works?

**Comment by ghost** [comment]
An older version of portable Chrome does nothing as well, Brave as well.

**Comment by georgysaumen** [comment]
As I know, from version 96 Chrome started to change all to L1 not L3, so if
you want to use you have to downgrade Chrome to 95 or update your chrome
from 94 to 95 and block automatic update or use Brave browser.

Vào Th 6, 22 thg 10, 2021 lúc 23:18 VitusCitrus ***@***.***>
đã viết:

**Comment by ghost** [comment]
I use chrome v. 94.0.4606.81 (Official Build) (64-bit), and have no issues.

Check the chrome version, by typing: chrome://version
![image](https://user-images.githubusercontent.com/33004135/138540564-4283bcc7-8701-4bae-bc05-a530406a8076.png)

**Comment by georgysaumen** [comment]
> I use chrome v. 94.0.4606.81 (Official Build) (64-bit), and have no issues.
> 
> Check the chrome version, by typing: chrome://version ![image](https://user-images.githubusercontent.com/33004135/138540564-4283bcc7-8701-4bae-bc05-a530406a8076.png)

Yes, all version under newest version (96 above) will work normally

**Comment by ghost** [comment]
I'm using a version of Chrome below 96 and get no keys found, the console log says: "Can't verify license request signature; either the platform is wrong or the key has changed!"
tried it on a couple of site, netflix included

**Comment by georgysaumen** [comment]
> I'm using a version of Chrome below 96 and get no keys found, the console log says: "Can't verify license request signature; either the platform is wrong or the key has changed!" tried it on a couple of site, netflix included

[WidevineCdm.zip](https://github.com/parnexcodes/widevine-l3-guesser-modified/files/7403124/WidevineCdm.zip)
 
Update 2 file on your Chrome folder, go to WidevineCDM on Chrome folder and replace that 2 Widevine CDM files

**Comment by ghost** [comment]
> > I'm using a version of Chrome below 96 and get no keys found, the console log says: "Can't verify license request signature; either the platform is wrong or the key has changed!" tried it on a couple of site, netflix included
> 
> [WidevineCdm.zip](https://github.com/parnexcodes/widevine-l3-guesser-modified/files/7403124/WidevineCdm.zip)
> 
> Update 2 file on your Chrome folder, go to WidevineCDM on Chrome folder and replace that 2 Widevine CDM files

Thank you! Working fine.

**Comment by barepixels** [comment]
Confirm it is working again.  Version 95.0.4638.54 (Official Build) (64-bit)  Thank you
C:\Program Files\Google\Chrome\Application\95.0.4638.54\WidevineCdm\_platform_specific\win_x64\

**Comment by wkremser** [comment]
hi, is there a chance to get these files for macos too?

**Comment by 84Sheva** [comment]
>CDM has been updated I think.

Google has fixed the extension and i cannot get key for decrypt through the extension anymore. Can you give a look with this and create new ?

**Comment by georgysaumen** [comment]
At present, after u update chrome, widevinecdm on chrome will change to
newest ver is L1 cdm not L3 cdm anymore. L1 cdm no one share, i believe
because is die very soon

Vào Th 6, 3 thg 12, 2021 lúc 01:18 84Sheva ***@***.***> đã
viết:

**Comment by Sipherdrakon** [comment]
L1 is hardware specific and hardcoded into devices, so I highly doubt they changed to L1. But all the same the extension no longer works. Sorry.

**Comment by jackbosa90** [comment]
Can anyone tell me if in version 94.0.4606.54 of chrome the extension still works? I downgraded chrome to this version, replaced the 2 dlls as informed, but it didn't work. If it still works, could someone share/make the correct extension file available for me to test? Thanks.

**Comment by georgysaumen** [comment]
No, it doesn't.

All it revoked, u need to dump your personal L3 CDM through this (
https://github.com/wvdumper/dumper) or wait for leak new Guesser

Vào CN, 2 thg 1, 2022 vào lúc 20:14 jackbosa90 ***@***.***>
đã viết:
