### ISSUE TITLE
unable to find mpd on some websites

### ISSUE THREAD

**Issue by techno-arch** [parnexcodes/widevine-l3-guesser-modified#3]
unable to find mpd on 
youtube movies
google play movies and tv
netflix

no links show up in the extension but it still gets the keys

**Comment by techno-arch** [comment]
i have found how to find the video stream for netflex over here
https://www.reddit.com/r/Piracy/comments/m2s72k/widevine_l3_decrypter_netflix/gqne1td?utm_source=share&utm_medium=web2x&context=3

**Comment by parnexcodes** [comment]
Not all websites use mpd , some use m3u8 format
